"""
Converts logged pairwise comparisons (comparisons.jsonl) into a single
numeric preference-strength score per image, using the Bradley-Terry
model (via the choix library).

Output: a dict {image_filename: score}, also saved to scores.json

Generated by Claude Sonnet 5, reviewed and implemented.
"""

import json
from pathlib import Path

import choix

DATASET_DIR = Path("C:/the-oracle-of-my-vision/pipeline/sampled_renamed")  # adjust to your real folder
LOG_PATH = Path("C:/the-oracle-of-my-vision/pipeline/results/comparisons.jsonl")
SCORES_OUTPUT_PATH = Path("C:/the-oracle-of-my-vision/pipeline/results/scores.json")


def load_all_images():
    return sorted([
        p.name for p in DATASET_DIR.iterdir()
        if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}
    ])


def load_comparisons_log():
    entries = []
    with open(LOG_PATH, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                entries.append(json.loads(line))
    return entries


def build_choix_comparisons(all_images, log_entries):
    # choix needs each image mapped to an integer index
    image_to_idx = {name: i for i, name in enumerate(all_images)}

    comparisons = []  # list of (winner_idx, loser_idx) tuples
    for entry in log_entries:
        winner_name = entry["winner"]
        loser_name = entry["image_a"] if entry["winner"] == entry["image_b"] else entry["image_b"]

        winner_idx = image_to_idx[winner_name]
        loser_idx = image_to_idx[loser_name]
        comparisons.append((winner_idx, loser_idx))

    return comparisons, image_to_idx


def compute_scores():
    all_images = load_all_images()
    log_entries = load_comparisons_log()

    if not log_entries:
        print("No comparisons found in the log — nothing to score.")
        return

    comparisons, image_to_idx = build_choix_comparisons(all_images, log_entries)

    scores = choix.ilsr_pairwise(len(all_images), comparisons)
    # scores[i] is now a numeric preference strength for image i

    idx_to_image = {i: name for name, i in image_to_idx.items()}
    image_scores = {idx_to_image[i]: float(scores[i]) for i in range(len(all_images))}

    # sort for readability: highest preference score first
    ranked = dict(sorted(image_scores.items(), key=lambda x: x[1], reverse=True))

    with open(SCORES_OUTPUT_PATH, "w") as f:
        json.dump(ranked, f, indent=2)

    print(f"Computed scores for {len(ranked)} images. Saved to {SCORES_OUTPUT_PATH}")
    print("\nTop 5 preferred:")
    for name, score in list(ranked.items())[:5]:
        print(f"  {name}: {score:.4f}")
    print("\nBottom 5 preferred:")
    for name, score in list(ranked.items())[-5:]:
        print(f"  {name}: {score:.4f}")

    return ranked


if __name__ == "__main__":
    compute_scores()